version: '3.8'
services:
  db:
    image: postgres:14
    container_name: tripmateai-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - tripmateai-data:/var/lib/postgresql/data
      - ./db/backup:/backup


  elasticsearch:
    image: elastic/elasticsearch:8.15.2
    container_name: tripmateai-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  redis:
    image: redis:7
    container_name: tripmateai-redis
    ports:
      - "16379:6379"
    restart: unless-stopped
    
  pg_backup:
    build:
      context: .
      dockerfile: Dockerfile.pgbackup
    container_name: tripmateai-pgbackup
    depends_on:
      - db
    volumes:
      - ./scripts:/scripts
      - ./db/backup:/backup
      - ./logs:/logs
    restart: unless-stopped

volumes:
  tripmateai-data:
  esdata: