"""add partial index on users.created_at for active users

Revision ID: ac700eb44bf8
Revises: 446588133005
Create Date: 2025-04-24 22:55:25.959383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac700eb44bf8'
down_revision: Union[str, None] = '446588133005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_active_created_at', 'users', ['created_at'], unique=False, postgresql_where=sa.text("use_yn = 'Y' AND delete_yn = 'N'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_active_created_at', table_name='users', postgresql_where=sa.text("use_yn = 'Y' AND delete_yn = 'N'"))
    # ### end Alembic commands ###
